# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from auth import auth_pb2 as auth_dot_auth__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AuthServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authenticate = channel.unary_unary(
        '/auth.AuthService/Authenticate',
        request_serializer=auth_dot_auth__pb2.AuthRequest.SerializeToString,
        response_deserializer=auth_dot_auth__pb2.AuthResponse.FromString,
        )
    self.Validate = channel.unary_unary(
        '/auth.AuthService/Validate',
        request_serializer=auth_dot_auth__pb2.ValidateRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AuthServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Authenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Validate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=auth_dot_auth__pb2.AuthRequest.FromString,
          response_serializer=auth_dot_auth__pb2.AuthResponse.SerializeToString,
      ),
      'Validate': grpc.unary_unary_rpc_method_handler(
          servicer.Validate,
          request_deserializer=auth_dot_auth__pb2.ValidateRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'auth.AuthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
