# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import accounts_pb2 as accounts_dot_accounts__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AccountServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/account_service.AccountService/List',
        request_serializer=accounts_dot_accounts__pb2.ListAccountsRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.ListAccountsResponse.FromString,
        )
    self.GetById = channel.unary_unary(
        '/account_service.AccountService/GetById',
        request_serializer=accounts_dot_accounts__pb2.GetByIdRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.GetByEmail = channel.unary_unary(
        '/account_service.AccountService/GetByEmail',
        request_serializer=accounts_dot_accounts__pb2.GetByEmailRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.AuthenticateByEmail = channel.unary_unary(
        '/account_service.AccountService/AuthenticateByEmail',
        request_serializer=accounts_dot_accounts__pb2.AuthenticateByEmailRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.GeneratePasswordToken = channel.unary_unary(
        '/account_service.AccountService/GeneratePasswordToken',
        request_serializer=accounts_dot_accounts__pb2.GeneratePasswordTokenRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.GeneratePasswordTokenResponse.FromString,
        )
    self.ResetPassword = channel.unary_unary(
        '/account_service.AccountService/ResetPassword',
        request_serializer=accounts_dot_accounts__pb2.ResetPasswordRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.ConfirmAccount = channel.unary_unary(
        '/account_service.AccountService/ConfirmAccount',
        request_serializer=accounts_dot_accounts__pb2.ConfirmAccountRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.Create = channel.unary_unary(
        '/account_service.AccountService/Create',
        request_serializer=accounts_dot_accounts__pb2.CreateAccountRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.Update = channel.unary_unary(
        '/account_service.AccountService/Update',
        request_serializer=accounts_dot_accounts__pb2.UpdateAccountRequest.SerializeToString,
        response_deserializer=accounts_dot_accounts__pb2.Account.FromString,
        )
    self.Delete = channel.unary_unary(
        '/account_service.AccountService/Delete',
        request_serializer=accounts_dot_accounts__pb2.DeleteAccountRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AccountServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetByEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthenticateByEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GeneratePasswordToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetPassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConfirmAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=accounts_dot_accounts__pb2.ListAccountsRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.ListAccountsResponse.SerializeToString,
      ),
      'GetById': grpc.unary_unary_rpc_method_handler(
          servicer.GetById,
          request_deserializer=accounts_dot_accounts__pb2.GetByIdRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'GetByEmail': grpc.unary_unary_rpc_method_handler(
          servicer.GetByEmail,
          request_deserializer=accounts_dot_accounts__pb2.GetByEmailRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'AuthenticateByEmail': grpc.unary_unary_rpc_method_handler(
          servicer.AuthenticateByEmail,
          request_deserializer=accounts_dot_accounts__pb2.AuthenticateByEmailRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'GeneratePasswordToken': grpc.unary_unary_rpc_method_handler(
          servicer.GeneratePasswordToken,
          request_deserializer=accounts_dot_accounts__pb2.GeneratePasswordTokenRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.GeneratePasswordTokenResponse.SerializeToString,
      ),
      'ResetPassword': grpc.unary_unary_rpc_method_handler(
          servicer.ResetPassword,
          request_deserializer=accounts_dot_accounts__pb2.ResetPasswordRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'ConfirmAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ConfirmAccount,
          request_deserializer=accounts_dot_accounts__pb2.ConfirmAccountRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=accounts_dot_accounts__pb2.CreateAccountRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=accounts_dot_accounts__pb2.UpdateAccountRequest.FromString,
          response_serializer=accounts_dot_accounts__pb2.Account.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=accounts_dot_accounts__pb2.DeleteAccountRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'account_service.AccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
