version: "2"

services:
  # 3rd Party Services
  # ambassador:
  #   image: quay.io/datawire/ambassador:0.38.0
  #   ports:
  #   # expose port 80 via 8080 on the host machine
  #   - 8080:80
  #   volumes:
  #   # mount a volume where we can inject configuration files
  #   - ./ambassador/config:/ambassador/ambassador-config

  # Custom Services
  accounts:
    build: ./accounts
    working_dir: /code
    command: bash -c "python create_tables.py && python create_user.py && python app.py"
    ports:
      - "22222:22222"
    volumes:
      - ./accounts:/code
    # environment:
    #   - DATABASE_URL=
